Add static lenses
LSSTDESC/sims_GCRCatSimInterface pull request #56
Opened 2018-08-10 17:40 UTC by mpwiesner

Here is the new pull request to replace #42

2018-08-13 19:14 UTC, danielsf requested changes
I haven't had a chance to run this end-to-end (I am between sessions at the Project/Community Workshop).

There are some stylistic changes I would like to request, though.

2018-08-13 19:14 UTC, danielsf commented on bin.src/om10_lensing_equations.py
> +def lensed_sersic_2d(xi1, xi2, yi1, yi2, source_cat, lens_cat):
This method doesn't appear to be used, and I don't think it would work given the references to `ole` below, which is not defined in the scope of this module.  If I am correct that it is not needed, please remove it.

2018-08-13 19:14 UTC, danielsf commented on bin.src/om10_lensing_equations.py
> +import os
Please add docstrings to the methods in this module so that we know how to maintain them in the future.

2018-08-13 19:14 UTC, danielsf commented on bin.src/lensed_agn.py
> +#!/usr/bin/env python
Is this script still used, or has it been supplanted by `bin.src/generate_lensed_hosts_agn.py`?

If it is no longer needed, please remove it.

2018-08-13 19:14 UTC, danielsf commented on bin.src/om10_lensing_equations.py
> +import os
`bin.src/` should be reserved for scripts that we expect users to run directly.  It looks to me like this file is just a module of utility functions that other scripts move.  If I am correct, please move it into `python/desc/sims/GCRCatSimInterface`.  You can then import it from other files by changing the relevant import statements to
```
from desc.sims.GCRCatSimInterface.om10_lensing_equations import ....
```
in place of
```
from om10_lensing_equations import ...
```

2018-08-13 19:14 UTC, danielsf commented on bin.src/om10_lensing_equations.py
> +
Please include an `__all__` declaration in this module defining which methods should be imported by
```
from om10_lensing_equations import *
```

2018-08-13 19:14 UTC, danielsf commented on python/desc/sims/GCRCatSimInterface/HostImages.py
> +class hostImage(object):
Please include a docstring indicating what this class is meant to be used for.

Also include definitions of the parameters we should feed to the class' `__init__` method.

2018-08-13 19:14 UTC, danielsf commented on python/desc/sims/GCRCatSimInterface/InstanceCatalogWriter.py
> +            written_catalog_names.append('agn_'+gal_name)
This line looks like an unneeded duplicate of line 382

2018-08-13 19:14 UTC, danielsf commented on python/desc/sims/GCRCatSimInterface/InstanceCatalogWriter.py
> +        if host_image_dir is None:
It is possible to instantiate `InstanceCatalogWriter` with `sprinkler=False`, in which case the sprinkler is not run.  In that case, the script should probably not try to include these lens hosts, correct?

2018-08-13 19:14 UTC, danielsf commented on bin.src/generate_lensed_hosts_sne.py
> +import numpy as np
Please include function outputs in all docstrings

2018-08-13 19:14 UTC, danielsf commented on bin.src/generate_lensed_hosts_agn.py
> +import numpy as np
Please include function outputs in all docstrings

2018-08-27 20:52 UTC, danielsf requested changes
When I ran the catalog generating script, I got a catalog with rows like
```
object 23530138124385 53.173935 -28.049795 16.239364 galaxySED/Const.12E10.1Z.spec.gz 0.620000 0 0 0 0 0 2353013857_16.239364008_bulge.fits 0.01 0 CCM 0.201541 2.877095 CCM 0.022699 3.100000
```
Note that the name of the FITS file does not have any directory information included.  I assume this was supposed to be specified by `host_image_dir` (which was not `None` when I generated this catalog).

Also note the (small) in-line stylistic changes requested.

2018-08-27 20:52 UTC, danielsf commented on python/desc/sims/GCRCatSimInterface/HostImages.py
> +    ra_center: the right ascension of the center of the field
Specify units for `ra_center`, `dec_center`, and `fov`

2018-08-27 20:52 UTC, danielsf commented on python/desc/sims/GCRCatSimInterface/om10_lensing_equations.py
> +        x position of the lens
specify units for x0 and y0

2018-08-27 20:52 UTC, danielsf commented on python/desc/sims/GCRCatSimInterface/om10_lensing_equations.py
> +   x: float
specify units for x and y

2018-08-27 20:52 UTC, danielsf commented on python/desc/sims/GCRCatSimInterface/om10_lensing_equations.py
> +    xi1:float
specify units for all x*, y* args

2018-08-27 20:52 UTC, danielsf commented on python/desc/sims/GCRCatSimInterface/InstanceCatalogWriter.py
> +
Whitespace error

2018-08-27 20:52 UTC, danielsf commented on python/desc/sims/GCRCatSimInterface/InstanceCatalogWriter.py
> +
Whitespace error

2018-08-27 20:52 UTC, danielsf commented on bin.src/generateInstCat.py
> +                    default=os.path.join(os.environ['TWINKLES_DIR'],'data'))
Should `host_data_dir` default to `os.path.join(os.environ['SIMS_GCRCATSIMINTERFACE_DIR'], 'data')`?

That seems to be where the `generate_lensed_hosts_*.py` scripts write to.

2018-08-28 22:09 UTC, mpwiesner commented
@danielsf thank you for the comments.  I believe I addressed all the requested changes.

2018-08-28 23:16 UTC, danielsf approved these changes
Looks good.  Thanks for all of your patience, Matt.

2018-08-29 18:29 UTC, danielsf commented
If no one objects, I am going to merge this at the end of the day (5pm PDT) today.

2018-08-30 15:55 UTC, mpwiesner commented
Thanks, @danielsf.

2018-08-30 16:44 UTC, merged