U/danielsf/rebase/config
LSSTDESC/sims_GCRCatSimInterface pull request #68
Opened 2018-09-28 20:08 UTC by danielsf

This PR implements a lot of changes in the InstanceCatalog writing API.

- It alters `InstanceCatalogWriter.py` to output a detailed job log indicating which components (stars, bulges, disks, knots, AGN, SNe) have been completed after how much clock time

- It also makes it possible to pass in parameters to `generateInstCat.py` using a file containing a json-ized dict of prameters.  This makes slurm batch scripts that submit many InstanceCatalog generating jobs with identical parameters much cleaner.  I wasn't terribly careful when I thought through this function.  I just wanted something that would work during the big DC2 crunch weekend.  Please scrutinize my decisions.  There should be an example config file here

https://github.com/LSSTDESC/sims_GCRCatSimInterface/blob/u/danielsf/rebase/config/workspace/parallel/config_file_edison.json

Finally: some changes are made to allow us to use the faster AGN simulation techniques in the `u/danielsf/cosmodc2/agn` PR.

2018-09-29 19:58 UTC, jchiang87 requested changes
I just have a few suggested changes, otherwise this looks fine.

2018-09-29 19:58 UTC, jchiang87 commented on bin.src/generateInstCat.py
> +            config_dict = {}
It looks like setting these entries in `config_dict` is intended to document the command line arguments in the `status_file`.  In that case, it would be more compact to do
```
config_dict = {}
config_dict.update(args.__dict__)
```
instead of setting each arg explicitly.  The key names for `proper_motion` and `sprinkler` will have `enable_` prepended, which may be what we want anyway.

2018-09-29 19:58 UTC, jchiang87 commented on bin.src/generateInstCat.py
> +        for kk in config_dict:
As above, `args.__dict__.update(config_dict)` should work in place of the `for` loop.

2018-09-29 19:58 UTC, jchiang87 commented on python/desc/sims/GCRCatSimInterface/InstanceCatalogWriter.py
> +        self.config_dict = config_dict
Even thought we will probably never pass `config_dict=None`, we should probably still do
```
self.config_dict = config_dict if config_dict is not None else {}
```
since there's a `for` loop over `self.config_dict` below.

2018-10-01 18:58 UTC, danielsf commented on bin.src/generateInstCat.py
> +            config_dict = {}
Done

2018-10-01 18:58 UTC, danielsf commented on bin.src/generateInstCat.py
> +        for kk in config_dict:
Done

2018-10-01 18:59 UTC, danielsf commented on python/desc/sims/GCRCatSimInterface/InstanceCatalogWriter.py
> +        self.config_dict = config_dict
Done

2018-10-01 19:00 UTC, jchiang87 approved these changes

2018-10-01 19:03 UTC, merged