Issue/82/unlensed agn instance catalogs
LSSTDESC/sims_GCRCatSimInterface pull request #83
Opened 2020-02-06 00:02 UTC by jbkalmbach

This pull request is to enable AGN variability in instance catalogs with the new multiband tau. Instead of changing sims_catUtils and potentially breaking things for other uses there, I just took the code we needed out of sims_catutils and added it here with the necessary changes. This also adds another flag to `generateInstCat.py` to turn on/off AGN in instance catalogs.

2020-02-06 00:19 UTC, jbkalmbach commented
Successfully tested on NERSC with shifter image `lsstdesc/stack-sims-cat:w_2019_42-sims_w_2019_42` running command: `python generateInstCat.py --config_file ../workspace/run2.1/test_agn_config_file_2.1.ddf.json --fov 0.05 --ids 2500000 --agn_threads 2`

2020-02-06 20:35 UTC, jchiang87 requested changes
The code looks ok to me, but I'm not familiar enough with the catsim code to do a real review of  `Variability.py` module.  We should put the `cosmoDC2_agn.db` file in a more permanent place and update the test agn config file path.

2020-02-06 20:35 UTC, jchiang87 commented on workspace/run2.1/test_agn_config_file_2.1.ddf.json
> +"agn_db_name": "/global/cscratch1/sd/jchiang8/desc/Run2.2i/agn_catalog/2019-11-21/cosmoDC2_agn.db",
We should move this out of my scratch area and into some place like `/global/projecta/projectdirs/lsst/groups/SSim/DC2/cosmoDC2_v1.1.4` and rename the file appropriately.  I created that file using the code that's currently in master via #80 .

2020-02-10 15:44 UTC, jchiang87 commented on workspace/run2.1/test_agn_config_file_2.1.ddf.json
> +"agn_db_name": "/global/cscratch1/sd/jchiang8/desc/Run2.2i/agn_catalog/2019-11-21/cosmoDC2_agn.db",
I've copied that file to 
```
/global/projecta/projectdirs/lsst/groups/SSim/DC2/cosmoDC2_v1.1.4/agn_cosmoDC2_v1.1.4.db
```

2020-02-12 22:02 UTC, jbkalmbach commented
Ok, I updated the location for the AGN database. I also submitted a [related PR in `sims_catUtils`](https://github.com/lsst/sims_catUtils/pull/106) to stop the `None` files from appearing when running instance catalog generation.

2020-02-12 23:53 UTC, jchiang87 approved these changes
lgtm.

2020-02-13 19:50 UTC, jbkalmbach commented
If nobody has any other comments, I will merge this at 4pm Pacific this afternoon.

2020-02-14 02:59 UTC, merged